apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 061039800008.dkr.ecr.ap-northeast-2.amazonaws.com/lion-frontend/lion-backend:latest
          ports:
            - containerPort: 8080
